### ISSUE TITLE
losses.reset()

### ISSUE THREAD

**Issue by hchoi71** [GuoleiSun/MCIS_wsss#11]
Hello author, 

Thanks for sharing great work! 

Just simple question, why do we need loss.reset() in your train.py at every 1000 iteration? is that because of trying to solve CUDA out of memory issue? or something else?

**Comment by LOOKCC** [comment]
@hchoi71  loss.reset() is just for AverageMeter(a python class), not for the loss which backward(named loss_val in code). And  AverageMeter is statistic of loss, it's code is very simple, you can find it from this line in train.py:'from utils import AverageMeter'. And I think the author just want to have a look of the average loss in latest 1000 iteration, not the average loss from the training start.
