### ISSUE TITLE
No field named "interp_param".

### ISSUE THREAD

**Issue by gladcolor** [GuoleiSun/MCIS_wsss#3]
Got an error:  no field named "interp_param".
Could you help me to figure it out?

(testcaffe) HH@H:/media/HH/HD4T/Research/MCIS_wsss/segmentation/examples/seg$ python eval_res.py 0 exp2 model
here:  model
2020-08-11 14:45:59,101 eval_res.py [line:305] INFO Beginning loading dataset...
2020-08-11 14:45:59,104 eval_res.py [line:269] INFO Beginning caffe_forward...
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0811 14:45:59.343677  5337 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0811 14:45:59.343703  5337 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0811 14:45:59.343715  5337 _caffe.cpp:142] Net('./deploy_resnet_fov.prototxt', 1, weights='/media/HH/HD4T/Research/MCIS_wsss/segmentation/examples/seg/exp2/model/res_fov2a.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:307] Error parsing text-format caffe.NetParameter: 6364:84: Message type **"caffe.LayerParameter" has no field named "interp_param".**
F0811 14:45:59.347930  5337 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./deploy_resnet_fov.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by GuoleiSun** [comment]
Do you follow the the readme file to compile caffe and check if it is installed correctly. I think the problem is with caffe.
