### ISSUE TITLE
where is the implementation of co-attention 

### ISSUE THREAD

**Issue by vijosam** [GuoleiSun/MCIS_wsss#5]
Very nice work!

I am interested in the detailed implementation of co-attention and contrastive co-attention module, but I cannot find them in the code, neither in the prototxt (https://github.com/GuoleiSun/MCIS_wsss/blob/master/segmentation/examples/seg/deploy_resnet_fov.prototxt). Could you help me to point out the location of the codes? 

Thanks

**Comment by GuoleiSun** [comment]
Thanks for your interest. The attention code can be found here: https://github.com/GuoleiSun/MCIS_wsss/blob/7b1ed8982c29d5391bfe56b3e97051651e09e749/Classifier/models/vgg.py#L171
