### ISSUE TITLE
Code BUGs

### ISSUE THREAD

**Issue by wenbinTse** [GuoleiSun/MCIS_wsss#6]
Thanks for your work and code sharing. I'm trying to run the code and find there are lots of bugs in the code. For instance, there is no `train_data_loader_siamese_more_augumentation` object in `utils.loaddata` module. In the dataset implementation, `crop_size` is not used and how could you make sure the same tensor size among a mini-batch.

**Comment by GuoleiSun** [comment]
Thanks for your interest, I will check it and get back to you soon.

**Comment by wenbinTse** [comment]
Looking forward to the updating.

**Comment by GuoleiSun** [comment]
Thanks for your interest. The problem is solved.

**Comment by GuoleiSun** [comment]
I am closing this, let me know if you have other problems
