### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by aoyanl** [GuoleiSun/MCIS_wsss#7]
Hello, Mr. Sun, can you provide these data？Thanks you very much！！

--img_dir=/scratch_net/cyan/works/dataset-research/weakly-semantic-seg/VOCdevkit/VOC2012/JPEGImages/ \
--train_list=/srv/beegfs-benderdata/scratch/specta/data/guolei/datasets-research/weakly-semantic-seg/VOCdevkit/VOC2012/ImageSets/Segmentation/train_cls.txt \
--test_list=/srv/beegfs-benderdata/scratch/specta/data/guolei/datasets-research/weakly-semantic-seg/VOCdevkit/VOC2012/ImageSets/Segmentation/val_cls.txt \

**Comment by GuoleiSun** [comment]
Hello, thanks for your interest. The dataset is standard in WSSS. You can download it here https://drive.google.com/file/d/1uh5bWXvLOpE-WZUUtO77uwCB4Qnh6d7X/view

Thanks

**Comment by dorazhiyuyang** [comment]
Can you upload the two files in a separate link instead of with the images together? That's too large.
Thanks.
VOCdevkit/VOC2012/ImageSets/Segmentation/train_cls.txt
VOCdevkit/VOC2012/ImageSets/Segmentation/val_cls.txt
